# Generated by Django 2.1.7 on 2019-06-11 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('painel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao', models.TextField()),
                ('Link', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='vaga',
            name='Categoria',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vaga',
            name='Dono',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foto',
            name='Vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel.Vaga'),
        ),
    ]
