# Generated by Django 2.1.7 on 2019-06-11 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0002_auto_20190611_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='Dono',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
