# Generated by Django 2.1.7 on 2019-06-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0003_auto_20190611_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='Descricao',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='foto',
            old_name='Vaga',
            new_name='vaga',
        ),
        migrations.RenameField(
            model_name='vaga',
            old_name='Bairro',
            new_name='bairro',
        ),
        migrations.RenameField(
            model_name='vaga',
            old_name='Categoria',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='vaga',
            old_name='Cidade',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='vaga',
            old_name='Dono',
            new_name='dono',
        ),
        migrations.RenameField(
            model_name='vaga',
            old_name='Estado',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='vaga',
            old_name='Referencia',
            new_name='referencia',
        ),
        migrations.RenameField(
            model_name='vaga',
            old_name='Rua',
            new_name='rua',
        ),
        migrations.RenameField(
            model_name='vaga',
            old_name='Valor',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='foto',
            name='Link',
        ),
        migrations.AddField(
            model_name='foto',
            name='imagens',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
