# Generated by Django 2.1.7 on 2019-06-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0004_auto_20190611_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='rascunho',
            field=models.BooleanField(default=True),
        ),
    ]
